### ISSUE TITLE
Deprecation warning message using v1 tag

### ISSUE THREAD

**Issue by MikeMcC399** [richardsimko/update-tag#13]
## Deprecation warning

GitHub outputs the following warning when richardsimko/update-tag@v1 is used:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: richardsimko/update-tag@v1

## Suggestion

The [v1](https://github.com/richardsimko/update-tag/tree/v1) tag points to commit https://github.com/richardsimko/update-tag/commit/5bd0e05b035e02d5da3768dbdcfc4e5e0908623e which is equivalent to [v1.0.5](https://github.com/richardsimko/update-tag/releases/tag/v1.0.5).

Could the [v1](https://github.com/richardsimko/update-tag/tree/v1) tag be bumped to point to the latest version commit https://github.com/richardsimko/update-tag/commit/3c6952f9f47f93f3aaa9c957a5ddb04d61584d4d for [v1.0.6](https://github.com/richardsimko/update-tag/releases/tag/v1.0.6) instead?

**Comment by richardsimko** [comment]
Thanks for the report! It turned out that the action to do this automatically was broken since Github had deprecated things around input/output since I last updated anything. It's been fixed now and `v1` should point to the latest version.

**Comment by MikeMcC399** [comment]
@richardsimko 

Many thanks for fixing this! I noticed that you are also getting a deprecation warning in your action (see https://github.com/richardsimko/update-tag/actions/runs/3591248419). This does not affect the external usage of the action, but you might like to bump v2 to v3 in `checkout`:

https://github.com/richardsimko/update-tag/blob/b1d16647461afcdecbbf8b2706149876192b929f/.github/workflows/update-major-version.yml#L11

**Comment by richardsimko** [comment]
Thanks, I added renovate to keep dependencies up to date!
